name: bbn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - scanpy==1.9.8
    - scib==1.1.5
    - anndata==0.9.2
    - h5py==3.11.0
    - pandas==2.0.3
    - numpy==1.24.4
    - scipy==1.10.1
    - matplotlib==3.7.5
    - seaborn==0.13.2
    - scikit-learn==1.3.2
    - umap-learn==0.5.7
    - tqdm==4.67.1
    - torch==2.0.0+cu118
    - wandb==0.19.8
    - pyyaml
