damond:
  mode: imc
  data: /home/w29632hl/code/BatchEffect/BioBatchNet/DATA/IMC/subDamond_full.h5ad
  loss:
    recon: 10
    discriminator: 0.3
    classifier: 1
    kl_bio: 0.001
    kl_batch: 0.1
    ortho: 0.01
  trainer:
    sampling_fraction: 0.2

hoch:
  mode: imc
  data: /home/w29632hl/code/BatchEffect/BioBatchNet/DATA/IMC/HochSchulz.h5ad
  loss:
    recon: 10
    discriminator: 0.1
    classifier: 1
    kl_bio: 0.0
    kl_batch: 0.1
    ortho: 0.01
  trainer:
    sampling_fraction: 0.1

immucan:
  mode: imc
  data: /home/w29632hl/code/BatchEffect/BioBatchNet/DATA/IMC/IMMUcan.h5ad
  trainer:
    epochs: 30
  loss:
    recon: 10
    discriminator: 0.1
    classifier: 1
    kl_bio: 0.005
    kl_batch: 0.1
    ortho: 0.01

pancreas:
  mode: seq
  data: /home/w29632hl/code/BatchEffect/BioBatchNet/DATA/scRNA/pancreas.h5ad
  trainer:
    epochs: 50
  loss:
    recon: 10
    discriminator: 0.04
    classifier: 1
    kl_bio: 1.0e-06
    kl_batch: 0.01
    ortho: 0.0002
    kl_size: 0.002

macaque:
  mode: seq
  data: /home/w29632hl/code/BatchEffect/BioBatchNet/DATA/scRNA/macaque.h5ad
  trainer:
    epochs: 50
  loss:
    recon: 3
    discriminator: 0.02
    classifier: 0.02
    kl_bio: 1.0e-05
    kl_batch: 0.01
    ortho: 0.0002
    kl_size: 0.002

mousebrain:
  mode: seq
  data: /home/w29632hl/code/BatchEffect/BioBatchNet/DATA/scRNA/mousebrain.h5ad
  loss:
    recon: 2
    discriminator: 0.1
    classifier: 0.01
    kl_bio: 0.000001
    kl_batch: 0.01
    ortho: 0.001
    kl_size: 0.01

lung:
  mode: seq
  data: /home/w29632hl/code/BatchEffect/BioBatchNet/DATA/scRNA/lung_atlas.h5ad
  trainer:
    epochs: 100
  loss:
    recon: 10
    discriminator: 0.01
    classifier: 1
    kl_bio: 0.000001
    kl_batch: 0.01
    ortho: 0.0002
    kl_size: 0.002
