# base RNA config
n_gpu: 1
train_seed_list: null
eval_sampling_seed: [42]

arch:
  type: GeneVAE
  args:
    in_sz: 2000
    bio_encoder_hidden_layers: [500, 2000, 2000]
    batch_encoder_hidden_layers: [500]
    latent_sz: 20
    decoder_hidden_layers: [2000, 2000, 500]
    out_sz: 2000
    batch_classifier_layers_power: [500, 2000, 2000]
    batch_classifier_layers_weak: [128]
    cell_classifier_layers: [64, 32]

train_dataloader:
  type: DataLoader
  args:
    batch_size: 128
    shuffle: true
    num_workers: 0

eval_dataloader:
  type: DataLoader
  args:
    batch_size: 128
    shuffle: False
    num_workers: 0

optimizer:
  type: Adam
  args:
    lr: 0.00001
    weight_decay: 0.0001
    amsgrad: true

lr_scheduler:
  type: StepLR
  args:
    step_size: 50
    gamma: 0.1

trainer:
  epochs: 100
  save_dir: "./saved/"
  save_period: 20
  verbosity: 2
  early_stop: 15
  if_imc: False 