name: mousebrain
n_gpu: 1
train_seed_list: null
eval_sampling_seed: [42]

arch:
  type: GeneVAE
  args:
    in_sz: 2000
    bio_encoder_hidden_layers: [500, 2000, 2000]
    batch_encoder_hidden_layers: [500]
    latent_sz: 20
    decoder_hidden_layers: [2000, 2000, 500]
    out_sz: 2000
    batch_classifier_layers_power: [500, 2000, 2000]
    batch_classifier_layers_weak: [128]
    num_batch: 2
    cell_classifier_layers: [64, 32]

train_dataloader:
  type: DataLoader
  args:
    batch_size: 128
    shuffle: true
    num_workers: 0

eval_dataloader:
  type: DataLoader
  args:
    batch_size: 128
    shuffle: False
    num_workers: 0

optimizer:
  type: Adam
  args:
    lr: 0.00001
    weight_decay: 0.00001
    amsgrad: true

lr_scheduler:
  type: StepLR
  args:
    step_size: 50
    gamma: 0.1

trainer:
  epochs: 100
  save_dir: "./saved/"
  save_period: 20
  verbosity: 2
  monitor: "min val_loss"
  early_stop: 20
  if_imc: False
  sampling_fraction: 
    pancreas: 1
    macaque: 1
    mousebrain: 1

loss_weights:
  pancreas:
    recon_loss: 3
    discriminator: 0.02
    classifier: 0.02
    mmd_loss_1: 0.0000
    kl_loss_1: 0.000001
    kl_loss_2: 0.01
    ortho_loss: 0.0002
    kl_loss_size: 0.002
  macaque:
    recon_loss: 3
    discriminator: 0.02
    classifier: 0.02
    mmd_loss_1: 0.0000
    kl_loss_1: 0.000001
    kl_loss_2: 0.01
    ortho_loss: 0.0002
    kl_loss_size: 0.002
  mousebrain:
    recon_loss: 2
    discriminator: 0.3
    classifier: 0.01
    mmd_loss_1: 0
    kl_loss_1: 0.0005
    kl_loss_2: 0.010
    ortho_loss: 0.001
    kl_loss_size: 0.01
