# Baseline Configuration for Batch Effect Correction Methods

methods:
  Harmony:
    embed: X_harmony
    stochastic: false
  BBKNN:
    embed: X_pca
    stochastic: false
  Scanorama:
    embed: X_scanorama
    stochastic: false
  Combat:
    embed: X_combat
    stochastic: false
  SeuratCCA:
    embed: X_seurat_cca
    stochastic: false
  SeuratRPCA:
    embed: X_seurat_rpca
    stochastic: false
  FastMNN:
    embed: X_fastmnn
    stochastic: false
  scVI:
    embed: X_scvi
    stochastic: true
  iMAP:
    embed: X_imap
    stochastic: true
  MrVI:
    embed: X_mrvi
    stochastic: true

# Dataset configurations
datasets:
  subDamond_full:
    path: ../Data/IMC/h5ad_format/subDamond_full.h5ad
    mode: imc
    sampling_fraction: 0.2
    sampling_seed: 42
    seed_list: [42, 52, 62, 72, 82]

  HochSchulz:
    path: ../Data/IMC/h5ad_format/HochSchulz.h5ad
    mode: imc
    sampling_fraction: 0.1
    sampling_seed: 42
    seed_list: [42, 52, 62, 72, 82]

  IMMUcan_batch:
    path: ../Data/IMC/h5ad_format/IMMUcan_batch.h5ad
    mode: imc
    sampling_fraction: 1.0
    sampling_seed: 42
    seed_list: [42, 52, 62, 72, 82]

  pancreas:
    path: /home/w29632hl/code/BatchEffect/BioBatchNet/DATA/scRNA/pancreas.h5ad
    mode: seq
    sampling_fraction: 1.0
    sampling_seed: 42
    seed_list: [42, 52, 62, 72, 82]

  macaque:
    path: /home/w29632hl/code/BatchEffect/BioBatchNet/DATA/scRNA/macaque.h5ad
    mode: seq
    sampling_fraction: 1.0
    sampling_seed: 42
    seed_list: [42, 52, 62, 72, 82]

  SubMouseBrain:
    path: /home/w29632hl/code/BatchEffect/BioBatchNet/DATA/scRNA/mousebrain.h5ad
    mode: seq
    sampling_fraction: 1.0
    sampling_seed: 42
    seed_list: [42, 52, 62, 72, 82]

  lung:
    path: /home/w29632hl/code/BatchEffect/BioBatchNet/DATA/scRNA/lung_atlas.h5ad
    mode: seq
    sampling_fraction: 1.0
    sampling_seed: 42
    seed_list: [42, 52, 62, 72, 82]